name: Create Event Workflow

on:
  create

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "Create event triggered ✅"

      - name: Show event name
        run: echo "${{ github.event_name }}"
